<?php


/**
 * Implements hook_menu().
 */
function hello_menu() {
//  $items['admin/hello'] = array(
//    'title' => 'Hello',
//    'description' => 'Hello module.',
//    'page callback' => 'hello_main',
//    'access arguments' => array('access administration pages'),
//  );
//  return $items;
  
  return array(
    'admin/hello' => array(
      'title' => 'Hello',
      'description' => 'Hello module',
      'page callback' => 'hello_main',
      'access arguments' => array('access administration pages'),
    ),
  );
}

function hello_main() {
  return '<p> Hello ! </p>';
}

